from re import I
import timeit
from xml.dom.expatbuilder import theDOMImplementation
from curb_projection.msg._StaticObjectObsArray import StaticObjectObsArray
import message_filters
import rospy
import queue
from threading import Thread, Lock
from functools import partial

from typing import List, Dict
from numpy.typing import NDArray
from cv_bridge import CvBridge
from sensor_msgs.msg import Image, PointCloud2, PointField
from std_msgs.msg import Header, Bool
from visualization_msgs.msg import MarkerArray, Marker
from tf import TransformListener
from time import perf_counter

from .utils import Batch, BatchSample, ModelsStore, ColorGen, CITYSCAPES_CLASS_NAMES
from .semantic_keyframe import SemanticKeyframe
from .maskclip_semseg import MaskCLIPSemSeg
from .opengraph_semseg import OpenGraphSemSeg

from hdl_graph_slam.msg import Keyframe_msg

import numpy as np


class SemanticMap:
    def __init__(self):
        self.bridge = CvBridge()

        models_dir = rospy.get_param("~models_dir")
        self.pcl_output_topic = rospy.get_param("~pcl_output_topic")

        self.models = ModelsStore(models_dir)  # projection models for each cam

        # interpolating tf listener with a memory of 2 minutes
        self.tl = TransformListener(cache_time=rospy.Duration(120), interpolate=True)

        # consistent class colors generated by this object
        self.color_gen = ColorGen()

        # choice of segmentation: maskclip or OpenGraph
        self.use_maskclip = rospy.get_param("~use_maskclip")
        self.use_opengraph = rospy.get_param("~use_opengraph")
        if self.use_maskclip:
            rospy.loginfo("Using MaskCLIP for segmentation")
            self.segmentation_model = MaskCLIPSemSeg()
        elif self.use_opengraph:
            rospy.loginfo("Using OpenGraph pipeline for segmentation")
            self.segmentation_model = OpenGraphSemSeg()
        else:
            raise ValueError("Choose one segmentation pipeline")

        # dict mapping keyframe IDs to SemanticKeyframe object
        self.kf_store: Dict[int, SemanticKeyframe] = dict()
        self.kf_lock = Lock()

        # message queue for async processing
        self.msg_q = queue.Queue()
        self.batch_size = 1  # opengraph currently only supports batch size 1
        self.n_cams = 1  # 4

        # queue for storing the segmentation result before projection
        self.segmentation_results_q = queue.Queue()

        kf_topic = rospy.get_param("~keyframes_topic")
        self.approx_time_syncs = []
        for agent_no in range(3):
            kf_sub = message_filters.Subscriber(kf_topic, Keyframe_msg)
            image_subs = [
                message_filters.Subscriber(f"/robotcar_{agent_no}/stereo/left", Image),
                message_filters.Subscriber(f"/robotcar_{agent_no}/mono/right", Image),
                message_filters.Subscriber(f"/robotcar_{agent_no}/mono/rear", Image),
                message_filters.Subscriber(f"/robotcar_{agent_no}/mono/left", Image),
            ]
            self.approx_time_syncs.append(
                message_filters.ApproximateTimeSynchronizer(
                    [kf_sub] + image_subs, queue_size=40, slop=0.3
                )
            )
            # pass the agent no to callback by fixing the first argument
            self.approx_time_syncs[-1].registerCallback(
                partial(self.keyframe_callback, agent_no)
            )

        # self.build_object_map_sub = rospy.Subscriber(
        #     "build_semantic_map", Bool, self.build_object_map, queue_size=1
        # )

        self.keyframe_pub = rospy.Publisher(
            self.pcl_output_topic, PointCloud2, queue_size=32
        )

        self.objects_pub = rospy.Publisher(
            rospy.get_param("~objects_output_topic"),
            StaticObjectObsArray,
            queue_size=32,
        )

        self.global_map_pub = rospy.Publisher("semantic_map", PointCloud2, queue_size=1)

        # self.map_build_timer = rospy.Timer(rospy.Duration(15), self.pub_global_map)

        if rospy.get_param("~global_debug_map"):
            self.map_build_sub = rospy.Subscriber(
                "build_semantic_map", Bool, self.pub_global_map
            )
            self.legend_pub = rospy.Publisher(
                "semantic_legend_marker", MarkerArray, queue_size=10, latch=True
            )
            self.publish_legend()

        self.semseg_thread = Thread(target=self.semseg_processor)
        self.semseg_thread.start()

        self.keyframe_gen_thread = Thread(target=self.keyframe_generator)
        self.keyframe_gen_thread.start()

        rospy.loginfo("Semantic mapping node ready")

    def semseg_processor(self):
        """Consumes input samples from msg_q and generates object masks.
        Output written to the keyframe_queue.
        """
        batch: Batch = Batch(self.batch_size, self.n_cams)
        while not rospy.is_shutdown():
            try:
                if self.msg_q.qsize() > self.batch_size * 2:
                    rospy.logwarn_throttle(
                        10.0,
                        "Semantic mapping node input queue too large: "
                        + f"{self.msg_q.qsize()} batch size: {self.batch_size}",
                    )

                batch_sample: BatchSample = self.msg_q.get(timeout=1.0)
                batch.add_sample(batch_sample)
                if batch.is_full():
                    batch = self.generate_segments(batch)
                    assert batch.is_processed()
                    # store processed samples in output queue
                    for sample in batch.samples:
                        self.segmentation_results_q.put(sample)
                    # create empty batch
                    batch = Batch(self.batch_size, self.n_cams)
            except queue.Empty:
                continue

    def generate_segments(self, batch: Batch) -> Batch:
        assert batch.is_full() and not batch.is_processed()

        t0 = perf_counter()
        for cam_idx in range(batch.n_cams):
            imgs = batch.get_imgs(cam_idx)
            result = self.segmentation_model.process_batch(imgs)
            # save result in batch object
            # result is a tuple (object masks, classes, scores) for each image
            batch.store_results(cam_idx, result)
        t1 = perf_counter()
        rospy.logdebug(f"Segmentation took: {t1 - t0:.2f}s")

        return batch

    def keyframe_generator(self):
        """Consumes processed batch samples from feature_q and creates SemanticKeyframe objects
        in the kf store.
        """
        while not rospy.is_shutdown():
            try:
                if self.segmentation_results_q.qsize() > self.batch_size * 2:
                    rospy.logwarn_throttle(
                        10.0,
                        f"Semantic mapping node feature queue too large: {self.segmentation_results_q.qsize()}"
                        + " (projection is too slow)",
                    )

                batch_sample: BatchSample = self.segmentation_results_q.get(timeout=1.0)
                semantic_keyframe = SemanticKeyframe(batch_sample, self.models, self.tl)

                objects = semantic_keyframe.get_found_objects()
                self.objects_pub.publish(objects)
                # pcl2 = semantic_keyframe.get_pointcloud_msg()
                # self.keyframe_pub.publish(pcl2)

                with self.kf_lock:
                    assert (
                        batch_sample.kf.id not in self.kf_store.keys()
                    ), "Double processed keyframe"
                    self.kf_store[semantic_keyframe.id] = semantic_keyframe

            except queue.Empty:
                continue

    def keyframe_callback(
        self,
        agent_no,
        kf_msg: Keyframe_msg,
        front_img: Image,
        right_img: Image,
        left_img: Image,
        rear_img: Image,
    ):
        if kf_msg.agent_no != agent_no:
            return

        rospy.logdebug(
            f"received kf id: {kf_msg.id} stamp:{kf_msg.header.stamp}, image stamps: "
            f"{front_img.header.stamp}, {right_img.header.stamp}, {left_img.header.stamp}, {rear_img.header.stamp},"
        )

        # convert all img messages to cv2 and store headers seperate
        imgs: List[NDArray] = []
        img_headers: List[Header] = []
        cam_imgs = [front_img, right_img, left_img, rear_img]
        for img_msg in cam_imgs[:self.n_cams]:
            img_cv = self.bridge.imgmsg_to_cv2(img_msg, desired_encoding="rgb8")
            model = self.models.get_model(img_msg.header.frame_id)
            assert model is not None, f"Unknown camera: {img_msg.header.frame_id}"
            imgs.append(model.undistort(img_cv))
            img_headers.append(img_msg.header)

        # sort fields in the cloud by offset to avoid conversion problems
        if kf_msg.cloud.fields:
            kf_msg.cloud.fields.sort(key=lambda x: x.offset)

        batch_sample = BatchSample(kf_msg, img_headers, imgs)
        self.msg_q.put(batch_sample)

    def publish_legend(self):
        ma = MarkerArray()
        ma.markers = []

        if self.use_maskclip:
            class_names: List[str] = rospy.get_param("~maskclip_prompt").split(",")  # type: ignore
        elif self.use_opengraph:
            class_names: List[str] = CITYSCAPES_CLASS_NAMES

        for i, c in enumerate(class_names[::-1]):
            marker = Marker()
            marker.header.frame_id = "world"
            marker.header.stamp = rospy.Time.now()
            marker.ns = "semantic_legend"
            marker.id = i
            marker.type = marker.TEXT_VIEW_FACING
            marker.action = marker.ADD
            marker.text = c
            marker.pose.position.x = 140
            marker.pose.position.y = -70
            marker.pose.position.z = -10 - (i * 10)
            marker.pose.orientation.x = 0.0
            marker.pose.orientation.y = 0.0
            marker.pose.orientation.z = 0.0
            marker.pose.orientation.w = 1.0
            marker.scale.z = 8
            marker.color.a = 1.0
            color = self.color_gen.get_color(c)
            marker.color.r = color[0]
            marker.color.g = color[1]
            marker.color.b = color[2]
            ma.markers.append(marker)

        self.legend_pub.publish(ma)

    def pub_global_map(self, _=None):
        if not rospy.get_param("~global_debug_map"):
            rospy.loginfo("Global debug map disabled")
            return

        t0 = timeit.default_timer()
        rospy.loginfo("Publishing global map")

        all_pts = np.ndarray((0, 6), dtype=np.float32)
        classes = []
        with self.kf_lock:
            for _, kf in self.kf_store.items():
                pts = kf.get_xyzrgb(self.color_gen)
                if pts is None:
                    continue
                all_pts = np.vstack((all_pts, pts))

        if len(all_pts) == 0:
            rospy.loginfo("No points in global map")
            return

        # apply uniform downsampling
        all_pts = all_pts[::4]
        classes = classes[::4]

        # create pcl2 message
        pcl_msg = PointCloud2()
        pcl_msg.header.stamp = rospy.Time.now()
        pcl_msg.header.frame_id = "world"
        pcl_msg.height = 1
        pcl_msg.width = all_pts.shape[0]
        pcl_msg.fields = [
            PointField("x", 0, PointField.FLOAT32, 1),
            PointField("y", 4, PointField.FLOAT32, 1),
            PointField("z", 8, PointField.FLOAT32, 1),
            PointField("r", 12, PointField.FLOAT32, 1),
            PointField("g", 16, PointField.FLOAT32, 1),
            PointField("b", 20, PointField.FLOAT32, 1),
        ]
        pcl_msg.is_bigendian = False
        pcl_msg.point_step = 24
        pcl_msg.row_step = pcl_msg.point_step * all_pts.shape[0]
        pcl_msg.is_dense = True
        pcl_msg.data = all_pts.astype(np.float32).tobytes()

        te = timeit.default_timer()
        rospy.loginfo(f"built global map containing {len(all_pts)} points in: {te - t0:.2f}s")
        self.global_map_pub.publish(pcl_msg)
